# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.host_name = "Ubuntu14.04"
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network :hostonly, "10.10.10.42"
  config.vm.forward_port 80, 8080
  config.vm.forward_port 8983, 8983
  config.vm.forward_port 9000, 9000

  #config.vm.share_folder "puppet", "/tmp/puppet", "./puppet"
  config.vm.share_folder "shared", "/shared/", "."
  #config.vm.provision :shell do |shell|
 
end

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 8000, host: 8000,
    auto_correct: true
  config.vm.provision :shell, path: "bootstrap.sh"
end
